import { type ImageSourcePropType } from 'react-native';

/**
 * Registry of the OFFICIAL Bubo brand and mascot assets (see docs/brand-assets.md).
 * Files are app-sized copies generated by `npm run assets:build` from assets-source/ and are never
 * redrawn. `npm run assets:check` verifies this file references every official asset.
 * Never use emoji, Stitch mascots or generated art in place of these.
 */

export const buboBrand = {
  logoHorizontal: {
    source: require('../../assets/brand/bubo-logo-horizontal.png') as ImageSourcePropType,
    /** width / height of the trimmed logo */
    aspectRatio: 720 / 232,
    accessibilityLabel: 'Bubo — Read deeply.',
  },
  symbol: {
    source: require('../../assets/brand/bubo-symbol.png') as ImageSourcePropType,
    aspectRatio: 512 / 453,
    accessibilityLabel: 'Bubo',
  },
} as const;

export type BrandAssetId = keyof typeof buboBrand;

export const buboMascots = {
  main: require('../../assets/mascot/bubo-main.png'),
  neutral: require('../../assets/mascot/bubo-neutral.png'),
  happy: require('../../assets/mascot/bubo-happy.png'),
  celebrating: require('../../assets/mascot/bubo-celebrating.png'),
  curious: require('../../assets/mascot/bubo-curious.png'),
  thinking: require('../../assets/mascot/bubo-thinking.png'),
  surprised: require('../../assets/mascot/bubo-surprised.png'),
  focused: require('../../assets/mascot/bubo-focused.png'),
  reading: require('../../assets/mascot/bubo-reading.png'),
  sleeping: require('../../assets/mascot/bubo-sleeping.png'),
  cheering: require('../../assets/mascot/bubo-cheering.png'),
  worried: require('../../assets/mascot/bubo-worried.png'),
  confident: require('../../assets/mascot/bubo-confident.png'),
  takingNotes: require('../../assets/mascot/bubo-taking-notes.png'),
  idea: require('../../assets/mascot/bubo-idea.png'),
  doubt: require('../../assets/mascot/bubo-doubt.png'),
  typing: require('../../assets/mascot/bubo-typing.png'),
  welcome: require('../../assets/mascot/bubo-welcome.png'),
  achievement: require('../../assets/mascot/bubo-achievement.png'),
  deepReading: require('../../assets/mascot/bubo-deep-reading.png'),
  review: require('../../assets/mascot/bubo-review.png'),
  loading: require('../../assets/mascot/bubo-loading.png'),
  empty: require('../../assets/mascot/bubo-empty.png'),
  error: require('../../assets/mascot/bubo-error.png'),
} satisfies Record<string, ImageSourcePropType>;

export type MascotPose = keyof typeof buboMascots;

/** Official pose names (brand board) — also used as accessible descriptions. */
export const mascotLabels: Record<MascotPose, string> = {
  main: 'Bubo, o mascote',
  neutral: 'Bubo neutro',
  happy: 'Bubo feliz',
  celebrating: 'Bubo comemorando',
  curious: 'Bubo curioso',
  thinking: 'Bubo pensando',
  surprised: 'Bubo surpreso',
  focused: 'Bubo focado',
  reading: 'Bubo lendo',
  sleeping: 'Bubo dormindo',
  cheering: 'Bubo animando',
  worried: 'Bubo preocupado',
  confident: 'Bubo confiante',
  takingNotes: 'Bubo anotando',
  idea: 'Bubo com uma ideia',
  doubt: 'Bubo com dúvida',
  typing: 'Bubo digitando',
  welcome: 'Bubo dando boas-vindas',
  achievement: 'Bubo com uma conquista',
  deepReading: 'Bubo em leitura profunda',
  review: 'Bubo revisando',
  loading: 'Bubo carregando',
  empty: 'Bubo descansando: nada por agora',
  error: 'Bubo segurando um aviso de erro',
};

/**
 * Semantic app states → closest official pose. Use these instead of picking poses ad hoc so the
 * mascot's emotional language stays consistent. States without a dedicated official asset map to
 * the semantically closest pose (documented in docs/brand-assets.md).
 */
export const mascotForState = {
  onboarding: 'welcome',
  emptyShelf: 'deepReading',
  emptyReview: 'empty',
  emptyCommunity: 'cheering',
  profile: 'main',
  reviewDue: 'review',
  recallPrompt: 'curious',
  recallCorrect: 'confident',
  recallPartial: 'doubt',
  recallIncorrect: 'worried',
  sessionComplete: 'celebrating',
  achievementUnlocked: 'achievement',
  streakAtRisk: 'worried',
  focusSession: 'focused',
  loading: 'loading',
  offline: 'sleeping',
  error: 'error',
  notFound: 'doubt',
} as const satisfies Record<string, MascotPose>;

export type MascotState = keyof typeof mascotForState;
