import { z } from 'zod';
import { createCycleRequestSchema, clubCyclesResponseSchema } from './cycles';
import {
  friendActionSchema,
  friendsResponseSchema,
  friendsFeedSchema,
  socialPreferencesSchema,
} from './friends';

import { achievementsResponseSchema } from './achievements';
import {
  blockRequestSchema,
  blocksResponseSchema,
  clubDetailSchema,
  clubMembersResponseSchema,
  clubPollDetailSchema,
  clubPollSchema,
  clubPollsResponseSchema,
  communityFeedResponseSchema,
  createPollRequestSchema,
  inviteCodeResponseSchema,
  invitePreviewSchema,
  joinByCodeRequestSchema,
  pollArgumentRequestSchema,
  pollArgumentSchema,
  pollVoteRequestSchema,
  reactionRequestSchema,
  reactionResponseSchema,
  clubPostSchema,
  clubPostsResponseSchema,
  clubReplySchema,
  clubsResponseSchema,
  clubTopicResponseSchema,
  createClubRequestSchema,
  createPostRequestSchema,
  createReplyRequestSchema,
  joinClubRequestSchema,
  moderationRequestSchema,
  moderationResponseSchema,
  reportRequestSchema,
  reportResponseSchema,
  moderationQueueSchema,
  globalModerationRequestSchema,
} from './community';
import { catalogBookResponseSchema, catalogSearchResponseSchema } from './catalog';
import { errorResponseSchema } from './errors';
import { memoryStatsResponseSchema } from './memory';
import { healthResponseSchema, readyResponseSchema } from './health';
import {
  meResponseSchema,
  onboardingRequestSchema,
  shelfEntrySchema,
  shelfResponseSchema,
} from './me';
import {
  createCardRequestSchema,
  dueCardsResponseSchema,
  recallCardSchema,
  reviewRequestSchema,
} from './recall';
import {
  addBookRequestSchema,
  createSessionRequestSchema,
  reviewResultSchema,
  sessionResultSchema,
  shelfEntryDetailSchema,
  statsResponseSchema,
  updateShelfEntryRequestSchema,
} from './shelf';

export const deleteResponseSchema = z.object({ deleted: z.literal(true) });

/** Paths relative to the `/v1` prefix. */
export const API_ROUTES = {
  health: '/health',
  ready: '/ready',
  openapi: '/openapi.json',
  /** Better Auth handler (sign-up, sign-in, sign-out, session, password reset). */
  auth: '/auth',
  me: '/me',
  onboarding: '/me/onboarding',
  stats: '/me/stats',
  memoryStats: '/me/memory',
  achievements: '/me/achievements',
  shelf: '/shelf',
  shelfEntry: '/shelf/:id',
  sessions: '/sessions',
  recallDue: '/recall/due',
  recallCards: '/recall/cards',
  recallCard: '/recall/cards/:id',
  recallReview: '/recall/cards/:id/review',
  catalogSearch: '/catalog/search',
  catalogBook: '/catalog/books/:catalogId',
  catalogIsbn: '/catalog/isbn/:isbn',
  clubs: '/clubs',
  club: '/clubs/:id',
  clubMembership: '/clubs/:id/membership',
  clubPosts: '/clubs/:id/posts',
  clubPost: '/clubs/:id/posts/:postId',
  clubReplies: '/clubs/:id/posts/:postId/replies',
  clubReply: '/clubs/:id/replies/:replyId',
  clubModeration: '/clubs/:id/moderation',
  reports: '/reports',
  blocks: '/blocks',
  block: '/blocks/:userId',
  clubsJoin: '/clubs/join',
  clubInvite: '/clubs/invite/:code',
  clubInviteCode: '/clubs/:id/invite-code',
  clubMembers: '/clubs/:id/members',
  clubCycles: '/clubs/:id/cycles',
  clubCycleClose: '/clubs/:id/cycles/:cycleId/close',
  clubPolls: '/clubs/:id/polls',
  clubPoll: '/clubs/:id/polls/:pollId',
  clubPollVote: '/clubs/:id/polls/:pollId/vote',
  clubPollArgument: '/clubs/:id/polls/:pollId/argument',
  reactions: '/reactions',
  communityFeed: '/community/feed',
  friends: '/community/friends',
  friend: '/community/friends/:userId',
  friendsFeed: '/community/friends-feed',
  socialPreferences: '/me/social-preferences',
  moderationQueue: '/me/moderation',
  /** Better Auth account deletion lives at /v1/auth/delete-user (documented, not in the registry). */
} as const;

/** Fills `:param` placeholders, e.g. `apiPath(API_ROUTES.shelfEntry, { id })`. */
export function apiPath(template: string, params: Record<string, string>): string {
  return template.replace(/:(\w+)/g, (_, key: string) => {
    const value = params[key];
    if (value === undefined) throw new Error(`Missing route param "${key}" for ${template}`);
    return encodeURIComponent(value);
  });
}

export type ApiRouteDefinition = {
  method: 'get' | 'post' | 'put' | 'patch' | 'delete';
  path: string;
  summary: string;
  tags: string[];
  /** Requires a Better Auth session cookie. */
  auth: boolean;
  requestBody?: z.ZodType;
  responses: Record<number, { description: string; schema: z.ZodType }>;
};

/** Registry used to generate the OpenAPI document. Add every new route here. */
export const API_ROUTE_DEFINITIONS: ApiRouteDefinition[] = [
  {
    method: 'get',
    path: API_ROUTES.friends,
    summary: 'Friends, incoming/outgoing requests and privacy preferences.',
    tags: ['community'],
    auth: true,
    responses: {
      200: { description: 'Own relationships (up to 200).', schema: friendsResponseSchema },
    },
  },
  {
    method: 'put',
    path: API_ROUTES.friend,
    summary: 'Request a shared-club reader, accept incoming request or remove relationship.',
    tags: ['community'],
    auth: true,
    requestBody: friendActionSchema,
    responses: { 200: { description: 'Relationships.', schema: friendsResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.friendsFeed,
    summary:
      'Up to 50 catalog-book reading activities shared by accepted friends, after consent. Never reflections.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Feed.', schema: friendsFeedSchema } },
  },
  {
    method: 'put',
    path: API_ROUTES.socialPreferences,
    summary: 'Own friendship and sharing preferences; sharing defaults off.',
    tags: ['me'],
    auth: true,
    requestBody: socialPreferencesSchema,
    responses: {
      200: { description: 'Preferences and relationships.', schema: friendsResponseSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.clubCycles,
    summary: 'Recent reading cycles of the shared club book. Members only.',
    tags: ['community'],
    auth: true,
    responses: {
      200: {
        description: 'Cycles with session-derived progress.',
        schema: clubCyclesResponseSchema,
      },
    },
  },
  {
    method: 'post',
    path: API_ROUTES.clubCycles,
    summary: 'Start one cycle and snapshot participants (owner only, idempotent id).',
    tags: ['community'],
    auth: true,
    requestBody: createCycleRequestSchema,
    responses: { 200: { description: 'Cycles.', schema: clubCyclesResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.clubCycleClose,
    summary: 'Close a cycle (owner only, idempotent).',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Cycles.', schema: clubCyclesResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.moderationQueue,
    summary:
      'Open community reports, configured moderators only. Query reveal=1 explicitly includes reported text.',
    tags: ['community'],
    auth: true,
    responses: {
      200: { description: 'Queue (at most 100 items).', schema: moderationQueueSchema },
    },
  },
  {
    method: 'post',
    path: API_ROUTES.moderationQueue,
    summary: 'Resolve reported content across clubs, configured moderators only.',
    tags: ['community'],
    auth: true,
    requestBody: globalModerationRequestSchema,
    responses: { 200: { description: 'Moderated.', schema: moderationResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.memoryStats,
    summary:
      'Recorded review self-assessments by day, book and time of day. Query: today, days (7|30|90|365), tz (UTC offset minutes).',
    tags: ['me'],
    auth: true,
    responses: { 200: { description: 'Review history.', schema: memoryStatsResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.achievements,
    summary: 'Cognitive level and achievements derived from recorded activity. Query: today.',
    tags: ['me'],
    auth: true,
    responses: { 200: { description: 'Achievements.', schema: achievementsResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.health,
    summary: 'Liveness probe (no database access).',
    tags: ['system'],
    auth: false,
    responses: { 200: { description: 'Service is alive.', schema: healthResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.ready,
    summary: 'Readiness probe (configuration + database connectivity).',
    tags: ['system'],
    auth: false,
    responses: {
      200: { description: 'Ready to serve traffic.', schema: readyResponseSchema },
      503: { description: 'A dependency is not ready.', schema: readyResponseSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.me,
    summary: 'The signed-in reader and onboarding state.',
    tags: ['me'],
    auth: true,
    responses: { 200: { description: 'Current reader.', schema: meResponseSchema } },
  },
  {
    method: 'put',
    path: API_ROUTES.onboarding,
    summary: 'Save onboarding answers (habit, goals, interests, optional first book).',
    tags: ['me'],
    auth: true,
    requestBody: onboardingRequestSchema,
    responses: { 200: { description: 'Onboarding completed.', schema: meResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.stats,
    summary: 'Reading stats from real sessions (XP, streak, this week). Query: today=YYYY-MM-DD.',
    tags: ['me'],
    auth: true,
    responses: { 200: { description: 'Stats.', schema: statsResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.shelf,
    summary: "The reader's shelf.",
    tags: ['shelf'],
    auth: true,
    responses: { 200: { description: 'Shelf entries.', schema: shelfResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.shelf,
    summary: 'Add a book to the shelf: a catalog pick ({catalogId}) or a manual entry.',
    tags: ['shelf'],
    auth: true,
    requestBody: addBookRequestSchema,
    responses: {
      201: { description: 'Created.', schema: shelfEntrySchema },
      409: { description: 'The book is already on the shelf.', schema: errorResponseSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.shelfEntry,
    summary: 'One shelf entry with its recent reading sessions, recall cards and reviews.',
    tags: ['shelf'],
    auth: true,
    responses: { 200: { description: 'Entry.', schema: shelfEntryDetailSchema } },
  },
  {
    method: 'patch',
    path: API_ROUTES.shelfEntry,
    summary: 'Change status, current page or page count.',
    tags: ['shelf'],
    auth: true,
    requestBody: updateShelfEntryRequestSchema,
    responses: { 200: { description: 'Updated entry.', schema: shelfEntrySchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.shelfEntry,
    summary: 'Remove a book from the shelf (and its sessions).',
    tags: ['shelf'],
    auth: true,
    responses: { 200: { description: 'Removed.', schema: deleteResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.sessions,
    summary: 'Record a finished focused reading session (updates progress, XP, streak).',
    tags: ['sessions'],
    auth: true,
    requestBody: createSessionRequestSchema,
    responses: { 201: { description: 'Session recorded.', schema: sessionResultSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.recallDue,
    summary: 'Recall cards due today or earlier. Query: today=YYYY-MM-DD.',
    tags: ['recall'],
    auth: true,
    responses: { 200: { description: 'Due cards.', schema: dueCardsResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.recallCards,
    summary: 'Create a recall card for a book on the shelf.',
    tags: ['recall'],
    auth: true,
    requestBody: createCardRequestSchema,
    responses: { 201: { description: 'Created.', schema: recallCardSchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.recallCard,
    summary: 'Delete a recall card.',
    tags: ['recall'],
    auth: true,
    responses: { 200: { description: 'Deleted.', schema: deleteResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.recallReview,
    summary: 'Grade a recall attempt (SM-2 reschedules the card). Idempotent on id.',
    tags: ['recall'],
    auth: true,
    requestBody: reviewRequestSchema,
    responses: {
      201: { description: 'Review recorded.', schema: reviewResultSchema },
      200: { description: 'Retry of an already recorded review.', schema: reviewResultSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.catalogSearch,
    summary: 'Search Google Books + Open Library (merged, de-duplicated). Query: q, limit.',
    tags: ['catalog'],
    auth: true,
    responses: {
      200: {
        description: 'Results (possibly partial, see sources).',
        schema: catalogSearchResponseSchema,
      },
      503: {
        description: 'No usable results and at least one catalog source failed.',
        schema: errorResponseSchema,
      },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.catalogBook,
    summary: 'One catalog book (details + cover candidates) and whether it is on the shelf.',
    tags: ['catalog'],
    auth: true,
    responses: {
      200: { description: 'Book.', schema: catalogBookResponseSchema },
      404: { description: 'Unknown catalog id.', schema: errorResponseSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.catalogIsbn,
    summary: 'Look up a book by ISBN-10/13 (barcode scanner).',
    tags: ['catalog'],
    auth: true,
    responses: {
      200: { description: 'Book.', schema: catalogBookResponseSchema },
      404: { description: 'No book with this ISBN.', schema: errorResponseSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.clubs,
    summary: "The reader's clubs and public clubs to discover. Query: q (name or book title).",
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Clubs.', schema: clubsResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.clubs,
    summary: "Create a club around a catalog book from the creator's shelf (creator = owner).",
    tags: ['community'],
    auth: true,
    requestBody: createClubRequestSchema,
    responses: {
      201: { description: 'Created.', schema: clubDetailSchema },
      409: { description: 'Club limit reached.', schema: errorResponseSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.club,
    summary: "One club, the reader's membership and page on its book.",
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Club.', schema: clubDetailSchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.club,
    summary: 'Delete a club and all its content (owner only).',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Deleted.', schema: deleteResponseSchema } },
  },
  {
    method: 'put',
    path: API_ROUTES.clubMembership,
    summary: 'Join (accepting the guidelines); adds the book to the shelf if missing. Idempotent.',
    tags: ['community'],
    auth: true,
    requestBody: joinClubRequestSchema,
    responses: { 200: { description: 'Joined.', schema: clubDetailSchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.clubMembership,
    summary: 'Leave a club (the owner deletes it instead).',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Left.', schema: deleteResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.clubPosts,
    summary:
      "Debates and book reviews (members only); query reviews=1 filters reviews before the limit. Content beyond the reader's page is locked, including ratings.",
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Topics.', schema: clubPostsResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.clubPosts,
    summary:
      'Open a debate or book review (reviewRating 1–5, body 30+ characters, kind discussion). Idempotent on id.',
    tags: ['community'],
    auth: true,
    requestBody: createPostRequestSchema,
    responses: {
      201: { description: 'Created.', schema: clubPostSchema },
      200: { description: 'Retry of an existing topic.', schema: clubPostSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.clubPost,
    summary: 'One topic with its replies. Query: reveal=1 to see content beyond your page.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Topic.', schema: clubTopicResponseSchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.clubPost,
    summary: 'Delete your topic, or remove one as the club owner.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Deleted.', schema: deleteResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.clubReplies,
    summary: "Reply to a topic (page never below the topic's). Idempotent on id.",
    tags: ['community'],
    auth: true,
    requestBody: createReplyRequestSchema,
    responses: {
      201: { description: 'Created.', schema: clubReplySchema },
      200: { description: 'Retry of an existing reply.', schema: clubReplySchema },
    },
  },
  {
    method: 'delete',
    path: API_ROUTES.clubReply,
    summary: 'Delete your reply, or remove one as the club owner.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Deleted.', schema: deleteResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.clubModeration,
    summary: 'Remove or restore a topic/reply (club owner). Resolves its open reports.',
    tags: ['community'],
    auth: true,
    requestBody: moderationRequestSchema,
    responses: { 200: { description: 'Moderated.', schema: moderationResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.reports,
    summary: 'Report a topic or reply. Idempotent per reader; 3 reports hide it for review.',
    tags: ['community'],
    auth: true,
    requestBody: reportRequestSchema,
    responses: { 200: { description: 'Reported.', schema: reportResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.blocks,
    summary: 'Readers you blocked.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Blocks.', schema: blocksResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.blocks,
    summary: 'Block a reader: their topics and replies disappear for you. Idempotent.',
    tags: ['community'],
    auth: true,
    requestBody: blockRequestSchema,
    responses: { 200: { description: 'Blocked.', schema: blocksResponseSchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.block,
    summary: 'Unblock a reader.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Unblocked.', schema: blocksResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.communityFeed,
    summary: "Newest topics and polls from the reader's clubs, spoiler-locked per club.",
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Feed.', schema: communityFeedResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.clubsJoin,
    summary: 'Join a club with an invite code (accepting the guidelines). Idempotent.',
    tags: ['community'],
    auth: true,
    requestBody: joinByCodeRequestSchema,
    responses: {
      200: { description: 'Joined.', schema: clubDetailSchema },
      404: { description: 'Unknown code.', schema: errorResponseSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.clubInvite,
    summary: 'What an invite code leads to, before joining.',
    tags: ['community'],
    auth: true,
    responses: {
      200: { description: 'Club preview.', schema: invitePreviewSchema },
      404: { description: 'Unknown code.', schema: errorResponseSchema },
    },
  },
  {
    method: 'post',
    path: API_ROUTES.clubInviteCode,
    summary: 'Replace the club invite code (owner). Old links stop working.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'New code.', schema: inviteCodeResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.clubMembers,
    summary: 'Members, their page on the club book and the page distribution (members only).',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Members.', schema: clubMembersResponseSchema } },
  },
  {
    method: 'get',
    path: API_ROUTES.clubPolls,
    summary: 'Club polls, newest first; spoiler-locked like topics (members only).',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Polls.', schema: clubPollsResponseSchema } },
  },
  {
    method: 'post',
    path: API_ROUTES.clubPolls,
    summary: 'Create a poll (2–4 options, 3 or 7 days). Idempotent on id.',
    tags: ['community'],
    auth: true,
    requestBody: createPollRequestSchema,
    responses: {
      201: { description: 'Created.', schema: clubPollSchema },
      200: { description: 'Retry of an existing poll.', schema: clubPollSchema },
    },
  },
  {
    method: 'get',
    path: API_ROUTES.clubPoll,
    summary: 'One poll with its arguments. Query: reveal=1 to see it beyond your page.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Poll.', schema: clubPollDetailSchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.clubPoll,
    summary: 'Delete your poll, or remove one as the club owner.',
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Deleted.', schema: deleteResponseSchema } },
  },
  {
    method: 'put',
    path: API_ROUTES.clubPollVote,
    summary: "Replace the reader's vote while the poll is open.",
    tags: ['community'],
    auth: true,
    requestBody: pollVoteRequestSchema,
    responses: {
      200: { description: 'Poll with results.', schema: clubPollSchema },
      409: { description: 'Poll closed.', schema: errorResponseSchema },
    },
  },
  {
    method: 'put',
    path: API_ROUTES.clubPollArgument,
    summary: "Write or edit the reader's argument for their vote.",
    tags: ['community'],
    auth: true,
    requestBody: pollArgumentRequestSchema,
    responses: { 200: { description: 'Argument.', schema: pollArgumentSchema } },
  },
  {
    method: 'delete',
    path: API_ROUTES.clubPollArgument,
    summary: "Delete the reader's own argument.",
    tags: ['community'],
    auth: true,
    responses: { 200: { description: 'Deleted.', schema: deleteResponseSchema } },
  },
  {
    method: 'put',
    path: API_ROUTES.reactions,
    summary: 'Turn a reaction (insight, idea, counterpoint) on or off on a topic or argument.',
    tags: ['community'],
    auth: true,
    requestBody: reactionRequestSchema,
    responses: { 200: { description: 'Counts.', schema: reactionResponseSchema } },
  },
];
