// Embed official PNGs byte for byte and existing colour tokens for Worker/CID emails.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.join(root, 'apps/api/src/services/email-artwork.generated.ts');
const sources = {
  logo: 'brand/bubo-logo-horizontal.png',
  welcome: 'mascot/bubo-welcome.png',
  doubt: 'mascot/bubo-doubt.png',
  confident: 'mascot/bubo-confident.png',
};
const colours = fs.readFileSync(path.join(root, 'apps/mobile/src/theme/colors.ts'), 'utf8');
const tokens = Object.fromEntries(
  ['purple', 'purpleDeep', 'purpleSoft', 'lavender', 'white', 'ink', 'inkMuted', 'line'].map(
    (name) => {
      const value = new RegExp(`\\b${name}: '(#[A-Fa-f0-9]+)'`).exec(colours)?.[1];
      if (!value) throw new Error(`Token de email ausente: ${name}`);
      return [name, value];
    },
  ),
);
const images = Object.fromEntries(
  Object.entries(sources).map(([name, source]) => [
    name,
    fs.readFileSync(path.join(root, 'apps/mobile/assets', source)).toString('base64'),
  ]),
);
const source = await prettier.format(
  '// Generated by scripts/email-assets.mjs. Official artwork, unchanged; do not edit.\n' +
    `export const emailPalette = ${JSON.stringify(tokens)} as const;\n` +
    `export const emailArtwork = ${JSON.stringify(images)} as const;\n`,
  { ...(await prettier.resolveConfig(output)), parser: 'typescript' },
);
if (process.argv.includes('--check')) {
  if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== source) {
    throw new Error('Assets de email desatualizados. Rode npm run email:assets.');
  }
  console.log('email:assets — 4 PNGs oficiais e 8 tokens verificados.');
} else {
  fs.writeFileSync(output, source);
  console.log('email:assets — PNGs oficiais e tokens preparados.');
}
